### ISSUE TITLE
Restore behavior where the link text is the unhashed db names

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette-hashed-urls#8]
Previously, the links from the main page of the site did not have the "-HASH" suffix. It would be better, imo, to not show this suffix to the user in the link text.

![Screenshot 2022-03-19 at 09-47-19 Labor Data _memory f7-8035c93 nlrb-0d2bab9 opdr-2c6ef14 old_nlrb-4d77db5 voluntary_recognitions-4421085 work_stoppages-4950813 lm20-568a8e9 chips-38c0485](https://user-images.githubusercontent.com/536941/159123669-7ca86265-bf57-49d0-990e-81752796c826.png)

So for the example the link text here would be "f7" not  "f7-8035c93", etc.

**Comment by simonw** [comment]
This is similar to:
- #9

But slightly harder to fix with metadata because the index page doesn't take the `metadata.title` into account at the moment: https://github.com/simonw/datasette/blob/764738dfcb16cd98b0987d443f59d5baa9d3c332/datasette/templates/index.html#L13

```html+jinja
    <h2 style="padding-left: 10px; border-left: 10px solid #{{ database.color }}"><a href="{{ urls.database(database.name) }}">{{ database.name }}</a>{% if database.private %} 🔒{% endif %}</h2>
```
I think that may be a bug in Datasette itself: if you set a custom metadata title for a database surely that should be shown on the index page?
